### ISSUE TITLE
Example code fails to build

### ISSUE THREAD

**Issue by oofus** [BlokasLabs/USBMIDI#3]
Hi. Trying to build the example code for USBMIDI and it's failing with the following message

src\usbmidi_pluggableusb.cpp:90:2: error: 'Fifo' does not name a type

  Fifo m_midiInFifo;

Seems not to be using the template to define the type, and fifo.h isn't included in usbmidi_pluggableusb.cpp.

This is V1.1.0 installed from within the Arduino IDE.

**Comment by gtrainavicius** [comment]
Hey, what board are you targeting?

**Comment by gtrainavicius** [comment]
Ok, I have just fixed the issue, tagged a v1.1.1 release. It should get picked up automatically by Arduino IDE eventually, but to get the fix sooner, just remove v1.1.0 USBMIDI library and do:

```bash
cd .../Arduino/libraries
git clone https://github.com/BlokasLabs/USBMIDI/
```

I've tested this Pluggable USB implementation with SparkFun ProMicro, works fine now. :)

Thank you for reporting the issue!

**Comment by oofus** [comment]
The board is a DIY-More Pro Micro. It's an equivalent of the Sparkfun ProMicro (Which I've used in the past) but it is recognised as a Leonardo.

Thanks for the quick fix, I'll try it out right now.

**Comment by oofus** [comment]
That has fixed the build issue, thanks. Now to test and write some of my own code !
